### ISSUE TITLE
Use original Lumo repo

### ISSUE THREAD

**Issue by grav** [grav/aws-lumo-cljs-runtime#7]
The README specifies to use a fork of Lumo, in order to make a static build, but the original Lumo repo as been updated by @arichiardi to support it. We should do this instead and eliminate the need of a fork

- [ ] Change Dockerfile to build using `BUILD_STATIC_BINARY=1 boot release`
- [ ] Update README to reflect this by pointing to the original Lumo repo

**Comment by grav** [comment]
Just tried building with `BUILD_STATIC_BINARY=1 boot release` on Mac. The resulting binary crashes:

```
$ ./build/lumo 
toine [ '/Users/grav/repo/lumo/build/lumo' ]
Lumo 1.9.0
ClojureScript 1.10.439
Node.js v12.0.0
 Docs: (doc function-name-here)
       (find-doc "part-of-name-here")
 Source: (source function-name-here)
 Exit: Control+D or :cljs/quit or exit

cljs.user=> /Users/grav/repo/lumo/build/lumo:1
"use strict";(function(){"use strict";var nn=Math.min,rn=Math.floor,an=Math.max,sn=String.fromCharCode;function e(e){return new Error("getopt: "+e)}function t(e,t,n){var r;for(yn(e||""===e,"optstring is required"),yn(e.constructor===String,"optstring must be a string"),yn(t,"argv is required"),yn(t.constructor===Array,"argv must be an array"),this.gop_argv=Array(t.length),this.gop_options={},this.gop_aliases={},this.gop_optind=void 0===n?2:n,this.gop_subind=0,r=0;r<t.length;r++)yn(t[r].constructor===String,"argv must be string array"),this.gop_argv[r]=t[r];this.parseOptstr(e)}function n(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}function r(e){for(var t=1;t<arguments.length;t++){var r=null==arguments[t]?{}:arguments[t],a=Object.keys(r);"function"==typeof Object.getOwnPropertySymbols&&(a=a.concat(Object.getOwnPropertySymbols(r).filter(function(e){return Object.getOwnPropertyDescriptor(r,e).enumerable}))),a.for

TypeError: hi.watchdogHasPendingSigint is not a function
    at Object.Ot (/Users/grav/repo/lumo/build/lumo:1:35481)
    at Object.cljs.core.string_print (<embedded>:1808:424)
    at Object.cljs.core.pr_with_opts (<embedded>:1821:240)
    at Function.cljs.core.println.cljs$core$IFn$_invoke$arity$variadic (<embedded>:1830:78)
    at Function.lumo.repl.print_error.cljs$core$IFn$_invoke$arity$3 (<embedded>:6645:51)
    at Function.lumo.repl.print_error.cljs$core$IFn$_invoke$arity$2 (<embedded>:6643:96)
    at Object.lumo.repl.handle_error (<embedded>:6647:272)
    at Object.lumo.repl.execute_text (<embedded>:6778:349)
    at Object.lumo.repl.execute_source (<embedded>:6779:366)
    at Object.lumo.repl.execute (<embedded>:6780:174)
```

**Comment by grav** [comment]
Seems to work with node 12.1.0.

**Comment by grav** [comment]
Building though the docker container from this repo, I end up getting a weird error:
```
docker run --rm -v /Users/grav/repo/lumo:/lumo ami-lumo

[snip]

make[1]: *** No rule to make target `/Users/grav/repo/lumo/target/main.js', needed by `38bdff0821254942b9284d2e64d641d7cbdcda3b.intermediate'.  Stop.
make[1]: *** Waiting for unfinished jobs....
rm 88ef92d03823f4c5dc51d99466b5509573543fee.intermediate
make[1]: Leaving directory `/lumo/tmp/node/12.0.0/node-v12.0.0/out'
make: *** [node] Error 2
....> ERROR: The release executable has not been generated. This indicates a failure in the build process. There is likely additional information above.
```
Not sure how the volume path arg to `docker` ends up inside an error msg in the docker container?

**Comment by arichiardi** [comment]
I think I get the same and it might be due to https://github.com/grav/aws-lumo-cljs-runtime/issues/5#issuecomment-487775926 but haven't tried yet.

**Comment by arichiardi** [comment]
Is this still a problem? I think we were able to build it eventually?

**Comment by grav** [comment]
Yes, it works well! I'll kept this issue open as a reminder to update the README :-)

**Comment by grav** [comment]
The README has now been updated to point to the BUILD.md file.
